output "cluster_id" { value = azurerm_kubernetes_cluster.main.id }
output "cluster_name" { value = azurerm_kubernetes_cluster.main.name }
output "cluster_fqdn" { value = azurerm_kubernetes_cluster.main.fqdn }
output "kube_config_raw" { value = azurerm_kubernetes_cluster.main.kube_config_raw
  sensitive = true }
output "host" { value = azurerm_kubernetes_cluster.main.kube_config[0].host
  sensitive = true }
output "identity_principal_id" { value = azurerm_kubernetes_cluster.main.identity[0].principal_id }
output "kubelet_identity_id" { value = azurerm_kubernetes_cluster.main.kubelet_identity[0].object_id }
output "kv_secrets_identity_id" { value = azurerm_kubernetes_cluster.main.key_vault_secrets_provider[0].secret_identity[0].object_id }
